### ISSUE TITLE
Extract; Illegal characters in path

### ISSUE THREAD

**Issue by ed65love** [akeeba/nativexplatform#10]
Gday all, please excuse me if this is a beginner question, but when extracting a website using AXW 4.0.3.19824 created on a Mac onto my Windows PC, I get the above error.

Does that mean the extract has stopped without completing?

I'm wondering if there's a dynamic rename option, even if it's ugly, so that the extract can complete.

Thanks from down under!

**Comment by nikosdion** [comment]
Two possibilities.

**You are using the wrong JPS password (I think this is most likely in your case)**. Retry extracting using the correct password. The extraction cannot validate the password. It will blindly decrypt the archive with whatever password you give it. This typically results in extracting a small amount (usually just one) of files with long, strange, obviously junk names before it crashes with an error. _This is by design_ and makes sure that there is no quick way for an attacker to brute force the password in the archive.

**Your archive contains filenames with characters that are invalid on Windows**. Certain characters that are valid on *NIX systems such as macOS, Linux and FreeBSD are invalid on Windows, e.g. the question mark. Also, Windows has a limit of 260 Unicode character for the full path to a file. Try extracting the archive in an immediate subdirectory of the windows system drive (e.g. `C:\Extracted Site`) using the Ignore Most Errors option in eXtract Wizard.

**Comment by ed65love** [comment]
It was #2, so it looks like there's not much to be done. I'll see if I can find a Unix box to extract to.

Thanks for your prompt reply!
