### ISSUE TITLE
Extraction Fails

### ISSUE THREAD

**Issue by topwebs** [akeeba/nativexplatform#2]
Tested the app and it failed on first extraction with error "Illegal characters in path" The file name that it stopped on had a question mark. When the Test without Extracting box was checked, the test concluded successfully.

**Comment by nikosdion** [comment]
This is the expected and correct behaviour. See [Microsoft's documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx). The question mark is one of the forbidden characters.
