### ISSUE TITLE
 Invalid characters in path

### ISSUE THREAD

**Issue by jjnxpct** [akeeba/nativexplatform#4]
Hi! When trying to extract a jps file with Extract Wizard 4.0.2.19567 I get an eror: "Invalid characters in path" and I can not extract the jps archive.

I'm on windows 10.

**Comment by nikosdion** [comment]
You need to enter the correct password

**Comment by jjnxpct** [comment]
Yep, you're right. I changed the password and tried to use the old one ;-) Extraction went fine. Thanks.

**Comment by nikosdion** [comment]
You're welcome :)
