### ISSUE TITLE
Akeeba eXtract Wizard - OS X 10.12.5 not woking

### ISSUE THREAD

**Issue by hamby** [akeeba/nativexplatform#5]
The eXtract Wizard seems not to work under OS X 10.12.5. After open the program it closing directly afterwards.

Best Chris

**Comment by nikosdion** [comment]
Make sure you have installed Mono as explained in the download page.

Important note: only use the download link in the Mono page to install 
Mono. Installing Mono using Homebrew (or anything similar) will NOT work 
properly.

**Comment by hamby** [comment]
Thanks, sorry i missed Mono.
