### ISSUE TITLE
4.0.3: Windows10 install error warning ...

### ISSUE THREAD

**Issue by just4t** [akeeba/nativexplatform#6]
FYI, only ... Shown when trying to install / upgrade to 4.0.3, [Windows 10 alert](https://1drv.ms/i/s!AuZEMrA0wRV7gw2e4KR97jGQRecH) pop-up.

**Comment by nikosdion** [comment]
You have sent me a broken link with no further information.

In any case, the Windows 10 installer works just fine. I have tested it. Make sure you actually meet the requirements we discuss in the Download page.
