### ISSUE TITLE
4.0.3: Windows10 install error warning ... 2

### ISSUE THREAD

**Issue by just4t** [akeeba/nativexplatform#7]
Provided link before works at my end ...!?
Anyway, [here you have a new one](https://web.tresorit.com/l#IPsSCPG3brN17pM7wABPGg) through other way.
Hope this helps.
best.

**Comment by nikosdion** [comment]
So, _you_ told _your_ copy of Windows on _your_ computer to stop _you_ from running any application _you_ downloaded from the Internet unless _you_ click the button in the dialog, per the screenshot _you_ provided.
