### ISSUE TITLE
extract wizard: ignore file write errors does not ignore write errors for filenames longer than 260 char

### ISSUE THREAD

**Issue by welrachid** [akeeba/nativexplatform#9]
extract wizard
ignore file write errors does not ignore write errors for filenames longer than 260 char

To reproduce:
make a backup of a file where the path is longer than 260 char (which is possible on linux) and try to extract on windows.

solution: either take care of IO exception or "test" if path is longer than 260 (either source path or destination path) (i tried extracting directly on c:\a\ which didnt work)

Thanks

**Comment by nikosdion** [comment]
There was indeed something missing there. Thank you for the heads up!

Regarding your issue, you can always use Kickstart on a local web server. Its "Ignore most errors" option will let you extract your backup archive on Windows. The file with the super long path name will be skipped over.

**Comment by welrachid** [comment]
👍 
Confirmed that kickstart is able to "ignore" this error and therefore finish extract :)
